### ISSUE TITLE
[Doc] Update README with installation instructions 

### ISSUE THREAD

**Issue by katleiahramos** [katleiahramos/Bark-Park#10]
I would really love to make this project more open-source and developer friendly. 

Right now the the README doesn't include any notes about how a developer can pull down the code locally and get it up and running. 

Task
- Update README to include installation instructions (downloading dependencies like postgresql, node, ruby, rails, ect)

**Comment by mintii** [comment]
Hey @katleiahramos 
I'd be happy to help work on this for you

**Comment by katleiahramos** [comment]
fixed by #21
