### ISSUE TITLE
[Doc] Add Pull Request Process section to contributing.md

### ISSUE THREAD

**Issue by katleiahramos** [katleiahramos/Bark-Park#17]
After #16 is merged, it would be great to address the TODO to add the Pull Request Process. Since this is after the `Development` section that should describe the process for forking the repo, cloning it locally - we this section should probably include information about how to create a pull request and what to expect. For example: use the pull request template, # of reviewers required (maybe some reasoning behind that). 

### Tasks
- add documentation in the TODO under the `Pull Request Process` header

**Comment by sachinm78** [comment]
I will take this one.
