### ISSUE TITLE
[task] Fix Map CSS 

### ISSUE THREAD

**Issue by katleiahramos** [katleiahramos/Bark-Park#20]
### Current Behavior 
- Currently, the app is over flowing horizontally and scrolling to the right. See gif below. 

![demo video showing map scrolling to the right ](http://g.recordit.co/vtkgOoDDXC.gif)

### Expected Behavior 
- the app does not overflow and there is no ability to scroll horizontally

**Comment by sourcediz** [comment]
Hello Kat, I've fixed this up I was wondering how you would like the file structure for style sheets done? As I have to add styling to Map-container. Would you like me to pass the style inline or import a stylesheet to MapContainer.js e.g MapContainer.css and if so would you like the containers separated into their own folders

Cheers, excited for my first contribution on github

**Comment by katleiahramos** [comment]
@sourcediz Passing the style inline works! I'm excited as well, thanks so much for contributing!

**Comment by katleiahramos** [comment]
fixed by #24
